### ISSUE TITLE
Error when trying to use the lib

### ISSUE THREAD

**Issue by orangecoding** [trfv/google-calendar-api-client#1]
Error on startup:
```
document is not defined at CalendarApiClient.loadScript 
```

**Comment by trfv** [comment]
@orangecoding 
Thank you for your reporting!!! Could you please tell me how to reproduce it?

**Comment by orangecoding** [comment]
Mhm, I actually just imported and started it. I did not even use it (just the import throws the error)

**Comment by trfv** [comment]
1. what is your environment? browser? nodejs? browser is required.
https://stackoverflow.com/questions/32126003/node-js-document-is-not-defined

3. This is the instruction how to use this lib. Did you try this?
https://github.com/trfv/google-calendar-api-client#usage

**Comment by orangecoding** [comment]
Oh damn ok, I was trying to use it with nodejs. Maybe a hint in the readme would be good to state it's only working in a browser, not in nodejs.
